# Generated by Django 5.0.4 on 2024-05-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_icon', models.ImageField(upload_to='img')),
                ('app_name', models.CharField(max_length=100)),
                ('app_link', models.CharField(max_length=100)),
                ('app_category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('points', models.IntegerField(default=1)),
            ],
        ),
    ]
